server.port=8081
spring.datasource.url=jdbc:postgresql://db:5432/prova
spring.datasource.username=prova
spring.datasource.password=prova
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
